INSERT INTO apartment (APARTMENT_ID, APARTMENT_NUMBER, APARTMENT_CLASS)
VALUES (1, 101, 'LUXURIOUS' );
INSERT INTO apartment (APARTMENT_ID, APARTMENT_NUMBER, APARTMENT_CLASS)
VALUES (2, 102, 'CHEAP' );
INSERT INTO apartment (APARTMENT_ID, APARTMENT_NUMBER, APARTMENT_CLASS)
VALUES (3, 105, 'MEDIUM' );